using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace KyoS.Web.Migrations
{
    public partial class IntakeMedicalHistory : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "IntakeMedicalHistory",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Client_FK = table.Column<int>(type: "int", nullable: false),
                    DateSignatureLegalGuardian = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DateSignaturePerson = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DateSignatureEmployee = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PrimaryCarePhysician = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AddressPhysician = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    City = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    State = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ZipCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Diphtheria = table.Column<bool>(type: "bit", nullable: false),
                    Mumps = table.Column<bool>(type: "bit", nullable: false),
                    Poliomyelitis = table.Column<bool>(type: "bit", nullable: false),
                    RheumaticFever = table.Column<bool>(type: "bit", nullable: false),
                    WhoopingCough = table.Column<bool>(type: "bit", nullable: false),
                    Tuberculosis = table.Column<bool>(type: "bit", nullable: false),
                    ScarletFever = table.Column<bool>(type: "bit", nullable: false),
                    Hepatitis = table.Column<bool>(type: "bit", nullable: false),
                    HighBloodPressure = table.Column<bool>(type: "bit", nullable: false),
                    KidneyTrouble = table.Column<bool>(type: "bit", nullable: false),
                    KidneyStones = table.Column<bool>(type: "bit", nullable: false),
                    BloodInUrine = table.Column<bool>(type: "bit", nullable: false),
                    BurningUrine = table.Column<bool>(type: "bit", nullable: false),
                    PainfulUrination = table.Column<bool>(type: "bit", nullable: false),
                    EyeTrouble = table.Column<bool>(type: "bit", nullable: false),
                    HearingTrouble = table.Column<bool>(type: "bit", nullable: false),
                    Fractures = table.Column<bool>(type: "bit", nullable: false),
                    EarInfections = table.Column<bool>(type: "bit", nullable: false),
                    FrequentNoseBleeds = table.Column<bool>(type: "bit", nullable: false),
                    FrequentSoreThroat = table.Column<bool>(type: "bit", nullable: false),
                    Hoarseness = table.Column<bool>(type: "bit", nullable: false),
                    Allergies = table.Column<bool>(type: "bit", nullable: false),
                    Allergies_Describe = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StomachPain = table.Column<bool>(type: "bit", nullable: false),
                    BlackStools = table.Column<bool>(type: "bit", nullable: false),
                    NightSweats = table.Column<bool>(type: "bit", nullable: false),
                    FrequentVomiting = table.Column<bool>(type: "bit", nullable: false),
                    SkinTrouble = table.Column<bool>(type: "bit", nullable: false),
                    PainfulMuscles = table.Column<bool>(type: "bit", nullable: false),
                    PainfulJoints = table.Column<bool>(type: "bit", nullable: false),
                    BackPain = table.Column<bool>(type: "bit", nullable: false),
                    SeriousInjury = table.Column<bool>(type: "bit", nullable: false),
                    Surgery = table.Column<bool>(type: "bit", nullable: false),
                    Arthritis = table.Column<bool>(type: "bit", nullable: false),
                    Hemorrhoids = table.Column<bool>(type: "bit", nullable: false),
                    WeightLoss = table.Column<bool>(type: "bit", nullable: false),
                    FrequentHeadaches = table.Column<bool>(type: "bit", nullable: false),
                    Fainting = table.Column<bool>(type: "bit", nullable: false),
                    ConvulsionsOrFits = table.Column<bool>(type: "bit", nullable: false),
                    LossOfMemory = table.Column<bool>(type: "bit", nullable: false),
                    Nervousness = table.Column<bool>(type: "bit", nullable: false),
                    ChronicCough = table.Column<bool>(type: "bit", nullable: false),
                    CoughingOfBlood = table.Column<bool>(type: "bit", nullable: false),
                    VenerealDisease = table.Column<bool>(type: "bit", nullable: false),
                    FrequentColds = table.Column<bool>(type: "bit", nullable: false),
                    HeartPalpitation = table.Column<bool>(type: "bit", nullable: false),
                    ChestPain = table.Column<bool>(type: "bit", nullable: false),
                    ShortnessOfBreath = table.Column<bool>(type: "bit", nullable: false),
                    SwellingOfFeet = table.Column<bool>(type: "bit", nullable: false),
                    SwollenAnkles = table.Column<bool>(type: "bit", nullable: false),
                    ChronicIndigestion = table.Column<bool>(type: "bit", nullable: false),
                    VomitingOfBlood = table.Column<bool>(type: "bit", nullable: false),
                    Jaundice = table.Column<bool>(type: "bit", nullable: false),
                    Constipation = table.Column<bool>(type: "bit", nullable: false),
                    BloodyStools = table.Column<bool>(type: "bit", nullable: false),
                    Cancer = table.Column<bool>(type: "bit", nullable: false),
                    Diabetes = table.Column<bool>(type: "bit", nullable: false),
                    HayFever = table.Column<bool>(type: "bit", nullable: false),
                    Hernia = table.Column<bool>(type: "bit", nullable: false),
                    HeadInjury = table.Column<bool>(type: "bit", nullable: false),
                    Rheumatism = table.Column<bool>(type: "bit", nullable: false),
                    Epilepsy = table.Column<bool>(type: "bit", nullable: false),
                    VaricoseVeins = table.Column<bool>(type: "bit", nullable: false),
                    Anemia = table.Column<bool>(type: "bit", nullable: false),
                    InfectiousDisease = table.Column<bool>(type: "bit", nullable: false),
                    FamilyDiabetes = table.Column<bool>(type: "bit", nullable: false),
                    FamilyDiabetes_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyCancer = table.Column<bool>(type: "bit", nullable: false),
                    FamilyCancer_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyTuberculosis = table.Column<bool>(type: "bit", nullable: false),
                    FamilyTuberculosis_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyHeartDisease = table.Column<bool>(type: "bit", nullable: false),
                    FamilyHeartDisease_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyKidneyDisease = table.Column<bool>(type: "bit", nullable: false),
                    FamilyKidneyDisease_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyHighBloodPressure = table.Column<bool>(type: "bit", nullable: false),
                    FamilyHighBloodPressure_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyHayFever = table.Column<bool>(type: "bit", nullable: false),
                    FamilyHayFever_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyAsthma = table.Column<bool>(type: "bit", nullable: false),
                    FamilyAsthma_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyEpilepsy = table.Column<bool>(type: "bit", nullable: false),
                    FamilyEpilepsy_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyGlaucoma = table.Column<bool>(type: "bit", nullable: false),
                    FamilyGlaucoma_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilySyphilis = table.Column<bool>(type: "bit", nullable: false),
                    FamilySyphilis_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyNervousDisorders = table.Column<bool>(type: "bit", nullable: false),
                    FamilyNervousDisorders_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FamilyOther = table.Column<bool>(type: "bit", nullable: false),
                    FamilyOther_ = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HaveYouEverBeenPregnant = table.Column<bool>(type: "bit", nullable: false),
                    HaveYouEverHadComplications = table.Column<bool>(type: "bit", nullable: false),
                    HaveYouEverHadPainful = table.Column<bool>(type: "bit", nullable: false),
                    HaveYouEverHadExcessive = table.Column<bool>(type: "bit", nullable: false),
                    HaveYouEverHadSpotting = table.Column<bool>(type: "bit", nullable: false),
                    AreYouCurrently = table.Column<bool>(type: "bit", nullable: false),
                    AreYouPhysician = table.Column<bool>(type: "bit", nullable: false),
                    DoYouSmoke = table.Column<bool>(type: "bit", nullable: false),
                    DoYouSmoke_PackPerDay = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DoYouSmoke_Year = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ListAllCurrentMedications = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PerformingCertainMotions = table.Column<bool>(type: "bit", nullable: false),
                    AssumingCertainPositions = table.Column<bool>(type: "bit", nullable: false),
                    Hearing = table.Column<bool>(type: "bit", nullable: false),
                    Seeing = table.Column<bool>(type: "bit", nullable: false),
                    Speaking = table.Column<bool>(type: "bit", nullable: false),
                    Reading = table.Column<bool>(type: "bit", nullable: false),
                    Concentrating = table.Column<bool>(type: "bit", nullable: false),
                    Comprehending = table.Column<bool>(type: "bit", nullable: false),
                    BeingConfused = table.Column<bool>(type: "bit", nullable: false),
                    BeingDisorientated = table.Column<bool>(type: "bit", nullable: false),
                    Calculating = table.Column<bool>(type: "bit", nullable: false),
                    WritingSentence = table.Column<bool>(type: "bit", nullable: false),
                    Walking = table.Column<bool>(type: "bit", nullable: false),
                    Planned = table.Column<bool>(type: "bit", nullable: false),
                    Unplanned = table.Column<bool>(type: "bit", nullable: false),
                    Normal = table.Column<bool>(type: "bit", nullable: false),
                    Complications = table.Column<bool>(type: "bit", nullable: false),
                    Complications_Explain = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BirthWeight = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Length = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BreastFed = table.Column<bool>(type: "bit", nullable: false),
                    BottleFedUntilAge = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AgeWeaned = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FirstYearMedical = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AgeFirstWalked = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AgeFirstTalked = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AgeToiletTrained = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DescriptionOfChild = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProblemWithBedWetting = table.Column<bool>(type: "bit", nullable: false),
                    AndOrSoiling = table.Column<bool>(type: "bit", nullable: false),
                    Immunizations = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Documents = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IntakeMedicalHistory", x => x.Id);
                    table.ForeignKey(
                        name: "FK_IntakeMedicalHistory_Clients_Client_FK",
                        column: x => x.Client_FK,
                        principalTable: "Clients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_IntakeMedicalHistory_Client_FK",
                table: "IntakeMedicalHistory",
                column: "Client_FK",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "IntakeMedicalHistory");
        }
    }
}
